# Generated by Django 3.2 on 2022-05-23 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='200', upload_to='images/profile-images/', width_field='200')),
                ('phone_number', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20)),
                ('store_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('store_category', models.CharField(max_length=15)),
                ('store_abbv', models.CharField(blank=True, max_length=5, null=True)),
                ('store_products', models.ManyToManyField(blank=True, related_name='store_items', to='product.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(choices=[('ABOVE_ONLY', 'ABOVE_ONLY'), ('BALM_OF_GELLIED', 'BALM_OF_GELLIED'), ('GRACE', 'GRACE'), ('CHAMPTIONS', 'CHAMPTIONS'), ('SPLENDOR', 'SPLENDOR'), ('HOPE', 'HOPE'), ('LOVE', 'LOVE')], max_length=16)),
                ('room', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
