# Generated by Django 3.2.13 on 2022-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(help_text='name should be in uppercase!', max_length=20),
        ),
    ]
