# Generated by Django 3.2.18 on 2023-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('vendor', 'vendor'), ('student', 'student')], default='client', max_length=20),
        ),
    ]
