# Generated by Django 3.2.18 on 2023-07-26 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='profile',
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount'),
            preserve_default=False,
        ),
    ]
