# Generated by Django 3.2.13 on 2022-07-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(help_text='NAME SHOULD BE IN UPPERCASE!', max_length=20),
        ),
    ]
