# Generated by Django 3.2.18 on 2023-07-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_delivery_person'),
        ('users', '0002_wallet_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='product_details',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='orders',
            field=models.ManyToManyField(blank=True, to='product.Order'),
        ),
    ]
