# Generated by Django 3.2.18 on 2023-06-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('reversed', 'reversed'), ('credit', 'credit'), ('debit', 'debit'), ('failed', 'failed'), ('unknown', 'unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(editable=False, max_length=128, verbose_name='password'),
        ),
    ]
