# Generated by Django 3.2.18 on 2023-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230501_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverer',
            old_name='details',
            new_name='extra_details',
        ),
        migrations.AlterField(
            model_name='client',
            name='room',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
