# Generated by Django 3.2.13 on 2022-07-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
