# Generated by Django 3.2.13 on 2022-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_abbv',
        ),
        migrations.AddField(
            model_name='store',
            name='store_rank',
            field=models.FloatField(default=0),
        ),
    ]
