# Generated by Django 3.2.23 on 2024-01-14 06:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_store_school_store_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_timezone',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_phone_numbers',
            new_name='whatsapp_phone_numbers',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_country',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_open_hours',
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='NG', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_address_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online'), ('suspended', 'suspended')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StoreOpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.store')),
            ],
        ),
    ]
