# Generated by Django 3.2.18 on 2023-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_school_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('vendor', 'vendor'), ('student', 'student')], default='client', max_length=20, verbose_name='role'),
        ),
    ]
