# Generated by Django 3.2.13 on 2022-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_gender_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_hash',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Image Hash'),
        ),
    ]
