# Generated by Django 3.2.18 on 2023-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230502_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('reversed', 'reversed'), ('credit', 'credit'), ('debit', 'debit'), ('failed', 'failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=100, null=True),
        ),
    ]
