# Generated by Django 3.2.23 on 2024-01-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240114_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='is_active',
            new_name='is_approved',
        ),
    ]
