# Generated by Django 3.2.13 on 2022-07-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220626_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-store_rank']},
        ),
        migrations.RemoveField(
            model_name='deliverer',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hostel'),
        ),
    ]
