# Generated by Django 3.2.18 on 2023-07-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school'),
        ),
    ]
