# Generated by Django 3.2.18 on 2023-07-28 16:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_store_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=users.models.profile_image_directory_path),
        ),
    ]
