# Generated by Django 3.2.13 on 2022-07-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220703_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
            preserve_default=False,
        ),
    ]
