# Generated by Django 3.2.13 on 2022-10-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220930_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='bank_name',
        ),
    ]
