# Generated by Django 3.2.23 on 2024-01-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_active_store_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='whatsapp_phone_numbers',
            new_name='whatsapp_numbers',
        ),
    ]
