# Generated by Django 3.2.18 on 2023-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='uncleared_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=100, null=True),
        ),
    ]
