# Generated by Django 3.2.13 on 2022-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_vendor_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='floor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_floor',
            field=models.BooleanField(default=False),
        ),
    ]
