# Generated by Django 3.2.18 on 2023-08-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_linked_stores'),
        ('users', '0008_wallet_uncleared_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.order'),
        ),
    ]
