# Generated by Django 3.2.13 on 2022-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_vendor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
