# Generated by Django 3.2.23 on 2024-01-14 07:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240114_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='NG', max_length=2),
        ),
    ]
