# Generated by Django 3.2.23 on 2024-01-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_store_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online'), ('suspended', 'suspended')], default='online', max_length=20),
        ),
    ]
