# Generated by Django 3.2.13 on 2022-10-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_vendor_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(help_text='SHOULD BE IN UPPERCASE!', max_length=20),
        ),
    ]
