# Generated by Django 3.2.18 on 2023-08-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230801_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school'),
        ),
    ]
