# Generated by Django 3.2.23 on 2024-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
