# Generated by Django 3.2.18 on 2023-08-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_hostel_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
