# Generated by Django 3.2.13 on 2022-12-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('view', 'view'), ('click', 'click'), ('purchase', 'purchase'), ('add_to_items', 'add_to_items'), ('remove_from_order', 'remove_from_order'), ('add_to_order', 'add_to_order'), ('remove_from_items', 'remove_from_items')], max_length=20),
        ),
    ]
