# Generated by Django 3.2.23 on 2024-01-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_hostel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfield',
            name='value_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
