# Generated by Django 3.2.13 on 2022-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20221221_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
