# Generated by Django 3.2.23 on 2024-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240118_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryperson',
            options={'ordering': ['-is_verified', '-status'], 'verbose_name_plural': 'Delivery People'},
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='is_available',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='status',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online'), ('suspended', 'suspended')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeopenhours',
            name='day',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=10),
        ),
    ]
