# Generated by Django 3.2.18 on 2023-08-01 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230801_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.wallet'),
            preserve_default=False,
        ),
    ]
