# Generated by Django 3.2.23 on 2024-01-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240118_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryperson',
            options={'ordering': ['-is_approved', '-status'], 'verbose_name_plural': 'Delivery People'},
        ),
        migrations.RenameField(
            model_name='deliveryperson',
            old_name='is_verified',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='not_allowed_bash',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='not_allowed_locations',
        ),
    ]
