# Generated by Django 3.2.18 on 2023-08-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
