# Generated by Django 3.2.23 on 2024-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20240118_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='uncleared_balance',
            new_name='unsettled_balance',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending'), ('reversed', 'reversed'), ('unsettled', 'unsettled'), ('settled', 'settled')], default='pending', max_length=20),
        ),
    ]
