# Generated by Django 3.2.23 on 2024-01-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_wallet_unsettled_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_fee',
            new_name='transfer_fee',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('transfer', 'transfer')], max_length=20),
        ),
    ]
