# Generated by Django 3.2.18 on 2023-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_wallet_cleared_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('refund', 'refund'), ('credit', 'credit'), ('debit', 'debit'), ('failed', 'failed'), ('unknown', 'unknown')], max_length=20),
        ),
    ]
