# Generated by Django 3.2.18 on 2023-08-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
    ]
