# Generated by Django 3.2.18 on 2023-08-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_device_device_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='UserDevice',
        ),
    ]
