# Generated by Django 3.2.18 on 2023-08-05 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_device_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
