# Generated by Django 3.2.23 on 2024-01-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_storeopenhours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeopenhours',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=10, null=True),
        ),
    ]
