# Generated by Django 3.2.18 on 2023-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_userdevice_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.TextField(),
        ),
    ]
