# Generated by Django 3.2.23 on 2024-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='device_name',
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
