# Generated by Django 3.2.23 on 2024-02-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20240205_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.TextField(),
        ),
    ]
