# Generated by Django 3.2.18 on 2023-08-15 23:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userdevice_device_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='school',
            new_name='store_school',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_products',
        ),
        migrations.AddField(
            model_name='store',
            name='store_bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
        ),
        migrations.AddField(
            model_name='store',
            name='store_phone_numbers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='NG', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
