# Generated by Django 3.2.23 on 2024-03-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userdevice_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hide_balance',
            field=models.BooleanField(default=False),
        ),
    ]
