# Generated by Django 3.2.18 on 2023-08-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20230816_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_phone_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
