# Generated by Django 3.2.18 on 2023-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_store_store_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
