# Generated by Django 3.2.23 on 2024-04-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_wallet_hide_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_average_preparation_time',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
