# Generated by Django 3.2.18 on 2023-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_store_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_category',
        ),
        migrations.AddField(
            model_name='store',
            name='store_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
