# Generated by Django 3.2.23 on 2024-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_transaction__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending'), ('reversed', 'reversed'), ('unsettled', 'unsettled'), ('settled', 'settled'), ('on-hold', 'on-hold')], default='pending', max_length=20),
        ),
    ]
