# Generated by Django 3.2.23 on 2024-04-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_order_notifications_statuses'),
        ('users', '0029_alter_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.deliveryperson')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.store')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
