# Generated by Django 3.2.23 on 2024-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20240407_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('expired', 'expired')], max_length=20),
        ),
    ]
