# Generated by Django 3.2.18 on 2023-08-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20230817_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
