# Generated by Django 3.2.18 on 2023-08-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20230818_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
