# Generated by Django 3.2.23 on 2024-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_deliverynotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('sent', 'sent'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('expired', 'expired')], max_length=20),
        ),
    ]
