# Generated by Django 3.2.18 on 2023-08-18 13:19

from django.db import migrations, models
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20230818_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='school',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='school',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='website',
        ),
        migrations.AddField(
            model_name='school',
            name='domains',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.store_cover_image_directory_path),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
