# Generated by Django 3.2.23 on 2024-04-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_deliverynotification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gender_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gender'),
        ),
    ]
