# Generated by Django 3.2.23 on 2024-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_store_gender_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
