# Generated by Django 3.2.23 on 2024-04-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_store_store_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='is_on_delivery',
        ),
    ]
