# Generated by Django 3.2.18 on 2023-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_school_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='addresses',
        ),
        migrations.AddField(
            model_name='school',
            name='campuses',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='domains',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_categories',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone_numbers',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
    ]
