# Generated by Django 3.2.18 on 2023-08-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20230818_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='campuses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor'),
        ),
    ]
