# Generated by Django 3.2.18 on 2023-08-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20230820_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='campuses',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
