# Generated by Django 3.2.23 on 2024-04-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_delete_menu'),
        ('users', '0037_alter_deliverynotification_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='product.itemattribute')),
            ],
        ),
    ]
