# Generated by Django 3.2.18 on 2023-08-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20230820_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='country_code',
        ),
    ]
