# Generated by Django 3.2.23 on 2024-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
