# Generated by Django 3.2.18 on 2023-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_vendor_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='campuses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
