# Generated by Django 3.2.23 on 2024-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20240429_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
