# Generated by Django 3.2.23 on 2024-04-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20240430_0946'),
        ('users', '0041_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='product.itemattribute'),
        ),
    ]
