# Generated by Django 4.2.4 on 2023-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
