# Generated by Django 4.2.4 on 2023-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_transaction_status_transaction_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-updated_on']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('refund', 'refund'), ('credit', 'credit'), ('debit', 'debit')], max_length=20),
        ),
    ]
