# Generated by Django 4.2 on 2023-09-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_profile_is_student_profile_city_profile_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
