# Generated by Django 3.2.23 on 2024-08-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20240507_0827'),
        ('users', '0045_auto_20240507_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ItemAttribute'),
        ),
    ]
