# Generated by Django 4.2 on 2023-09-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_rename_client_student_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school'),
        ),
    ]
