# Generated by Django 3.2.23 on 2024-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_menu_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
