# Generated by Django 3.2.23 on 2025-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_transaction_settlement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='passcode',
            field=models.CharField(default='pbkdf2_sha256$260000$6I4rxEDGxi7QADj3tV1v0H$YuyYNeP/WQqCNsgaZtk8Cl98bsU8X0b4Oqc0epPrU5M=', editable=False, max_length=128, verbose_name='passcode'),
        ),
    ]
