# Generated by Django 4.2 on 2023-09-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_profile_city_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
    ]
