# Generated by Django 3.2.23 on 2025-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_wallet_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='passcode',
            field=models.CharField(default='pbkdf2_sha256$260000$fDJqPNKgVwqjSkoIAOAoO5$5ze9ZM6H1sXphKELJGcFHDsVSAyIsE4HTOzIl85GsRs=', editable=False, max_length=128, verbose_name='passcode'),
        ),
    ]
