# Generated by Django 3.2.23 on 2025-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_wallet_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='passcode',
            field=models.CharField(default='pbkdf2_sha256$260000$aiqjTZgNfm0fJsGxo0QHqK$U/v6RLFS7n6HQROhPp6y4eTev3EvWNP/l15DgAgTvhE=', editable=False, max_length=128, verbose_name='passcode'),
        ),
    ]
