# Generated by Django 4.2 on 2025-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_wallet_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='passcode',
            field=models.CharField(default='pbkdf2_sha256$600000$qDkjDGhk0iWrD189aEk88Z$csTzWAZ8XXwhZtm+fH4DZclC9t+aDA7GE9iwj82MaAk=', editable=False, max_length=128, verbose_name='passcode'),
        ),
    ]
