# Generated by Django 4.2.5 on 2023-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_transaction_fee_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
