# Generated by Django 4.2 on 2025-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_wallet_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='passcode',
            field=models.CharField(default='pbkdf2_sha256$600000$L3O7SUFaSh4qUOggqvWsft$gczB1CQziPqBFUwXJbjKaUIgj5dfimMguPp0oeoMjbg=', editable=False, max_length=128, verbose_name='passcode'),
        ),
    ]
