# Generated by Django 4.2.5 on 2023-09-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_transaction_fee_transaction_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_data',
        ),
    ]
