# Generated by Django 4.2.5 on 2023-09-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_transaction_transfer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
    ]
