# Generated by Django 4.2.5 on 2023-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_transaction_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway_transfer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
