# Generated by Django 4.2.5 on 2023-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_transaction_gateway_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_transfer_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending'), ('reversed', 'reversed')], default='pending', max_length=20),
        ),
    ]
