# Generated by Django 4.2.5 on 2023-09-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_transaction_gateway_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
