# Generated by Django 4.2.7 on 2023-11-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_store_created_at_alter_store_vendor_delete_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
