# Generated by Django 4.2.7 on 2023-11-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_store_created_at_alter_store_vendor_delete_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
