# Generated by Django 3.2.19 on 2023-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_delete_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryperson',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='gender',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='not_allowed_bash',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='not_allowed_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
