# Generated by Django 3.2.19 on 2023-11-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20231113_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='is_info_completed',
        ),
    ]
