# Generated by Django 3.2.19 on 2023-11-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_rename_is_verified_profile_is_info_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_info_completed',
        ),
    ]
