# Generated by Django 3.2.19 on 2023-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_profile_is_info_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='short_name',
        ),
        migrations.AddField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
