# Generated by Django 3.2.19 on 2023-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20231115_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='flat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
