# Generated by Django 3.2.19 on 2023-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
