# Generated by Django 3.2.19 on 2023-11-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hostel'),
        ),
    ]
