# Generated by Django 3.2.19 on 2023-11-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_useractivity_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
