# Generated by Django 3.2.19 on 2023-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_profile_phone_number_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
