# Generated by Django 3.2.19 on 2023-11-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_order_order_track_id'),
        ('users', '0078_alter_profile_phone_number_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order'),
        ),
    ]
