# Generated by Django 3.2.19 on 2023-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_profile_calling_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='calling_code',
        ),
        migrations.AddField(
            model_name='store',
            name='store_open_hours',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
    ]
