# Generated by Django 3.2.19 on 2023-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20231121_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calling_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
