# Generated by Django 3.2.19 on 2023-11-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_profile_calling_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='wallet',
        ),
    ]
