# Generated by Django 3.2.19 on 2023-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_remove_deliveryperson_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_menu',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_open_hours',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_rank',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
