# Generated by Django 3.2.19 on 2023-11-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20231127_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_menu',
            field=models.JSONField(blank=True, default=['All']),
        ),
    ]
