# Generated by Django 3.2.19 on 2023-11-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_alter_store_store_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='activity_message',
        ),
    ]
