# Generated by Django 3.2.19 on 2023-12-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_remove_useractivity_activity_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('view', 'view'), ('added_to_cart', 'added_to_cart'), ('purchased', 'purchased'), ('add_to_items', 'add_to_items'), ('remove_from_order', 'remove_from_order'), ('add_to_order', 'add_to_order'), ('remove_from_items', 'remove_from_items')], max_length=20),
        ),
    ]
