# Generated by Django 3.2.19 on 2023-12-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_auto_20231202_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
