# Generated by Django 3.2.19 on 2023-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_store_store_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='not_allowed_delivery_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
