# Generated by Django 3.2.19 on 2023-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_store_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='not_allowed_delivery_locations',
        ),
        migrations.AddField(
            model_name='store',
            name='has_physical_store',
            field=models.BooleanField(default=False),
        ),
    ]
