# Generated by Django 3.2.19 on 2023-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_auto_20231205_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
