# Generated by Django 3.2.19 on 2023-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_alter_store_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
