# Generated by Django 3.2.19 on 2023-12-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_store_store_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cleared_balance',
        ),
    ]
