# Generated by Django 3.2.23 on 2023-12-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_remove_wallet_cleared_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_hash',
        ),
    ]
