# Generated by Django 3.2.23 on 2023-12-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_remove_profile_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_address_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streetName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
