# Generated by Django 3.2.23 on 2023-12-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_auto_20231231_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='streetName',
            new_name='street_name',
        ),
    ]
