# Generated by Django 3.2.23 on 2023-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_rename_streetname_profile_street_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_required_fields',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
