# Generated by Django 3.2.23 on 2024-01-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_profile_has_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
