# Generated by Django 3.2.23 on 2024-01-03 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_auto_20240101_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='floor_count',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='is_floor',
        ),
        migrations.CreateModel(
            name='HostelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=10)),
                ('placeholder', models.CharField(max_length=100)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('is_loop', models.BooleanField(default=False)),
                ('loop_range', models.IntegerField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hostel')),
            ],
        ),
    ]
