# Generated by Django 3.2.23 on 2024-01-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_auto_20240103_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfield',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
