# Generated by Django 3.2.23 on 2024-01-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_hostelfield_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfield',
            name='is_required',
        ),
    ]
