# Generated by Django 3.2.23 on 2024-01-03 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_remove_hostelfield_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfield',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='school',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='hostelfield',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
            preserve_default=False,
        ),
    ]
