# Generated by Django 3.2.23 on 2024-01-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_auto_20240103_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelfield',
            options={'verbose_name': 'Hostel Arrangement Field', 'verbose_name_plural': 'Hostel Arrangement Fields'},
        ),
        migrations.AlterField(
            model_name='hostelfield',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
