# Generated by Django 3.2.23 on 2024-01-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_auto_20240103_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfield',
            name='loop_suffix',
            field=models.CharField(blank=True, choices=[('number', 'number'), ('alphabet', 'alphabet')], max_length=10, null=True),
        ),
    ]
