# Generated by Django 3.2.23 on 2024-01-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_hostelfield_loop_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelfield',
            old_name='prefix',
            new_name='loop_prefix',
        ),
    ]
