# Generated by Django 3.2.23 on 2024-01-03 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_rename_prefix_hostelfield_loop_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelfield',
            name='loop_prefix',
            field=models.CharField(blank=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostelfield',
            name='loop_suffix',
            field=models.CharField(blank=True, choices=[('number', 'number'), ('alphabet', 'alphabet')], max_length=10),
            preserve_default=False,
        ),
    ]
