# Generated by Django 3.2.23 on 2024-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_auto_20240103_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
