# Generated by Django 3.2.23 on 2024-01-03 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_alter_hostelfield_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfield',
            name='school',
        ),
        migrations.AddField(
            model_name='hostel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelfield',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hostel'),
            preserve_default=False,
        ),
    ]
