# Generated by Django 3.2.23 on 2024-01-03 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_auto_20240103_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostelfield',
            name='hostel',
        ),
        migrations.AddField(
            model_name='hostelfield',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
            preserve_default=False,
        ),
    ]
