# Generated by Django 3.2.23 on 2024-01-03 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_auto_20240103_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='fields',
            field=models.ManyToManyField(blank=True, to='users.HostelField'),
        ),
    ]
