# Generated by Django 3.2.18 on 2023-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_qty', models.IntegerField(default=0)),
                ('product_price', models.FloatField()),
                ('product_calories', models.IntegerField(default=0)),
                ('product_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('product_created_on', models.DateTimeField(auto_now_add=True)),
                ('product_clicks', models.IntegerField(default=0)),
                ('product_views', models.IntegerField(default=0)),
                ('product_slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-product_clicks'],
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('urlParamName', models.SlugField(unique=True)),
                ('_type', models.CharField(choices=[('TYPE', 'TYPE'), ('CATEGORY', 'CATEGORY')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(help_text='Upload Item Image.', upload_to=product.models.item_directory_path, verbose_name='Item Image')),
                ('item_image_webp', models.ImageField(blank=True, help_text='Upload Item Image In Webp Format.', null=True, upload_to=product.models.item_directory_path, verbose_name='Webp Item Image')),
                ('item_image_hash', models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Item Image Hash')),
                ('is_primary', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
