# Generated by Django 3.2.23 on 2024-01-05 15:41

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_qty', models.IntegerField(default=0)),
                ('has_qty', models.BooleanField(default=False, editable=False)),
                ('product_qty_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_calories', models.FloatField(default=0.0)),
                ('product_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('product_share_visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', editable=False, max_length=20)),
                ('store_menu_name', models.CharField(blank=True, default='Others', max_length=30)),
                ('product_created_on', models.DateTimeField(auto_now_add=True)),
                ('product_clicks', models.IntegerField(default=0)),
                ('product_views', models.IntegerField(default=0)),
                ('product_slug', models.SlugField(unique=True)),
                ('product_currency', models.CharField(default='NGN', max_length=20)),
                ('product_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('is_groupable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-product_clicks'],
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('urlParamName', models.SlugField(unique=True)),
                ('_type', models.CharField(choices=[('TYPE', 'TYPE'), ('CATEGORY', 'CATEGORY')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(help_text='Upload Item Image.', upload_to=product.models.item_directory_path, verbose_name='Item Image')),
                ('item_image_hash', models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Item Image Hash')),
                ('is_primary', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_track_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('order_status', models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('out-for-delivery', 'out-for-delivery'), ('no-delivery-person', 'no-delivery-person'), ('ready-for-pickup', 'ready-for-pickup'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], db_index=True, default='not-started', max_length=20)),
                ('overall_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('shipping', models.JSONField(default=dict)),
                ('stores_infos', models.JSONField(default=dict)),
                ('store_notes', models.JSONField(blank=True, default=dict)),
                ('delivery_people', models.JSONField(blank=True, default=list)),
                ('order_payment_currency', models.CharField(default='NGN', max_length=20)),
                ('order_payment_method', models.CharField(default='card', max_length=20)),
                ('order_payment_url', models.CharField(blank=True, editable=False, max_length=200)),
                ('order_payment_status', models.CharField(blank=True, choices=[('failed', 'failed'), ('success', 'success'), ('pending', 'pending')], editable=False, max_length=20, null=True)),
                ('delivery_person_note', models.CharField(blank=True, max_length=200, null=True)),
                ('order_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_confirm_pin', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.item')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
