# Generated by Django 3.2.23 on 2024-01-05 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='users_liked',
            field=models.ManyToManyField(blank=True, editable=False, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='linked_delivery_people',
            field=models.ManyToManyField(editable=False, related_name='linked_delivery_people', to='users.DeliveryPerson'),
        ),
        migrations.AddField(
            model_name='order',
            name='linked_items',
            field=models.ManyToManyField(editable=False, to='product.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='linked_stores',
            field=models.ManyToManyField(editable=False, to='users.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='product.itemattribute'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type', to='product.itemattribute'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'item')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'item')},
        ),
    ]
