# Generated by Django 3.2.13 on 2022-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='item',
            name='has_qty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
