# Generated by Django 3.2.18 on 2023-05-08 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='details',
            new_name='order_details',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='order_user',
        ),
        migrations.AddField(
            model_name='order',
            name='order_created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('failed', 'failed'), ('success', 'success')], default='failed', max_length=20),
        ),
    ]
