# Generated by Django 3.2 on 2022-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item_image',
            field=models.ImageField(upload_to='images/items/'),
        ),
    ]
