# Generated by Django 3.2.18 on 2023-06-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattribute',
            name='_type',
            field=models.CharField(choices=[('TYPE', 'TYPE'), ('CATEGORY', 'CATEGORY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
