# Generated by Django 3.2.18 on 2023-07-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_shipping_address',
            new_name='order_shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_details',
        ),
    ]
