# Generated by Django 3.2.18 on 2023-07-01 14:14

from django.db import migrations
import uuid
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
        model_name='rating',
        name='id',
        field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
    ),
    ]
