# Generated by Django 3.2.23 on 2024-01-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_item_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_category',
        ),
        migrations.AddField(
            model_name='item',
            name='product_categories',
            field=models.ManyToManyField(blank=True, related_name='product_categories', to='product.ItemAttribute'),
        ),
    ]
