# Generated by Django 3.2 on 2022-05-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_itemimage_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_calories',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
