# Generated by Django 3.2.13 on 2022-07-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220728_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='has_qty',
        ),
    ]
