# Generated by Django 3.2.18 on 2023-07-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230726_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_created_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_delivery_price',
            new_name='delivery_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_overall_price',
            new_name='overall_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_shipping',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_stores_infos',
            new_name='stores_infos',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_payment_id',
        ),
    ]
