# Generated by Django 3.2.18 on 2023-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230629_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='order_shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_stores_infos',
            field=models.JSONField(default=dict),
        ),
    ]
