# Generated by Django 3.2.18 on 2023-07-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_delivery_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-id', '-timestamp']},
        ),
    ]
