# Generated by Django 3.2.23 on 2024-01-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20240108_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemattribute',
            old_name='urlParamName',
            new_name='slug',
        ),
    ]
