# Generated by Django 3.2 on 2022-05-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_item_product_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('urlParamName', models.CharField(max_length=10)),
                ('_type', models.CharField(choices=[('TYPE', 'TYPE'), ('CATEGORY', 'CATEGORY')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.itemattribute'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='product.itemattribute'),
        ),
    ]
