# Generated by Django 3.2.18 on 2023-07-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_itemimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-is_primary', '-timestamp']},
        ),
    ]
