# Generated by Django 3.2.18 on 2023-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230512_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('failed', 'failed'), ('success', 'success'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
