# Generated by Django 3.2.18 on 2023-07-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230726_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='linked_items',
            field=models.ManyToManyField(editable=False, to='product.Item'),
        ),
    ]
