# Generated by Django 3.2 on 2022-05-26 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220523_1636'),
        ('product', '0005_auto_20220526_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattribute',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='product.itemattribute'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vendor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type', to='product.itemattribute'),
        ),
    ]
