# Generated by Django 3.2.13 on 2022-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220806_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='item_image_hash',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Item Image Hash'),
        ),
    ]
