# Generated by Django 3.2.23 on 2024-01-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_urlparamname_itemattribute_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_fee',
            new_name='service_fee',
        ),
    ]
