# Generated by Django 3.2.18 on 2023-07-01 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rating_new_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='new_id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
