# Generated by Django 3.2.18 on 2023-08-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_linked_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='not-started', max_length=20),
        ),
    ]
