# Generated by Django 3.2.23 on 2024-01-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_transaction_fee_order_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stores_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('ready-for-pickup', 'ready-for-pickup'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], db_index=True, default='not-started', max_length=20),
        ),
    ]
