# Generated by Django 3.2.18 on 2023-05-12 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_order_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
