# Generated by Django 3.2 on 2022-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220526_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='product_views',
            field=models.IntegerField(default=0),
        ),
    ]
