# Generated by Django 3.2.13 on 2022-10-05 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_vendor_bank_name'),
        ('product', '0006_itemimage_item_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.store'),
        ),
    ]
