# Generated by Django 3.2.8 on 2022-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220527_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattribute',
            name='urlParamName',
            field=models.SlugField(),
        ),
    ]
