# Generated by Django 3.2.18 on 2023-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20230512_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
