# Generated by Django 3.2.18 on 2023-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20230726_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='overall_price',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
