# Generated by Django 3.2.18 on 2023-08-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_qty_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
