# Generated by Django 3.2 on 2022-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_itemattribute_urlparamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='urlParamName',
            field=models.SlugField(unique=True),
        ),
    ]
