# Generated by Django 3.2.13 on 2022-12-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_item_product_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_calories',
            field=models.IntegerField(default=0),
        ),
    ]
