# Generated by Django 3.2.23 on 2024-01-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_activities_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_payment_currency',
            new_name='order_currency',
        ),
    ]
