# Generated by Django 3.2.18 on 2023-07-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230726_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
