# Generated by Django 3.2.18 on 2023-08-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_item_product_qty_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_is_groupable',
            field=models.BooleanField(default=False),
        ),
    ]
