# Generated by Django 3.2.18 on 2023-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_item_product_is_groupable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_is_groupable',
            new_name='is_groupable',
        ),
        migrations.AlterField(
            model_name='item',
            name='product_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
