# Generated by Django 3.2.23 on 2024-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_order_payment_currency_order_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
