# Generated by Django 3.2 on 2022-05-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220528_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
