# Generated by Django 3.2.18 on 2023-07-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20230727_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_payment_id',
        ),
    ]
