# Generated by Django 3.2.18 on 2023-07-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_order_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_method',
            field=models.CharField(default='card', max_length=20),
        ),
    ]
