# Generated by Django 3.2.18 on 2023-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_item_product_share_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_share_visibility',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', editable=False, max_length=20),
        ),
    ]
