# Generated by Django 3.2 on 2022-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_item_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
