# Generated by Django 3.2.18 on 2023-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20230824_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
