# Generated by Django 3.2 on 2022-05-30 14:09

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220528_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item_image',
            field=models.ImageField(upload_to=product.models.item_directory_path),
        ),
    ]
