# Generated by Django 3.2.23 on 2024-01-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_order_stores_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stores_infos',
            field=models.JSONField(default=list),
        ),
    ]
