# Generated by Django 3.2 on 2022-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_itemimage_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_images',
            field=models.ManyToManyField(related_name='product_image', to='product.ItemImage'),
        ),
    ]
