# Generated by Django 4.2.5 on 2023-09-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='not-started', max_length=20),
        ),
    ]
