# Generated by Django 3.2.23 on 2024-01-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_store_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('ready-for-pickup', 'ready-for-pickup'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('refunded', 'refunded')], db_index=True, default='not-started', max_length=20),
        ),
    ]
