# Generated by Django 3.2 on 2022-06-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_item_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_images',
            field=models.ManyToManyField(null=True, related_name='product_image', to='product.ItemImage'),
        ),
    ]
