# Generated by Django 3.2.18 on 2023-06-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
