# Generated by Django 3.2.18 on 2023-06-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_role'),
        ('product', '0014_remove_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.profile'),
            preserve_default=False,
        ),
    ]
