# Generated by Django 3.2.23 on 2024-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store_menu_name',
            field=models.CharField(blank=True, default='OTHERS', max_length=30),
        ),
    ]
