# Generated by Django 3.2.23 on 2024-01-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_item_store_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_message',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(blank=True, choices=[('failed', 'failed'), ('success', 'success'), ('pending', 'pending'), ('refunded', 'refunded')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('ready-for-pickup', 'ready-for-pickup'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('failed', 'failed')], db_index=True, default='not-started', max_length=20),
        ),
    ]
