# Generated by Django 4.2.5 on 2023-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_order_transaction_fee_alter_item_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_calories',
            field=models.FloatField(default=0.0),
        ),
    ]
