# Generated by Django 3.2 on 2022-06-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_itemimage_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
