# Generated by Django 3.2.18 on 2023-06-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
