# Generated by Django 3.2.13 on 2022-06-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
        ('product', '0018_auto_20220612_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-product_clicks']},
        ),
        migrations.AlterField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vendor'),
        ),
    ]
