# Generated by Django 3.2.19 on 2023-11-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_item_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_currency',
            field=models.CharField(default='NGN', max_length=20),
        ),
    ]
