# Generated by Django 3.2.18 on 2023-06-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rating_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_on',
        ),
    ]
