# Generated by Django 3.2.19 on 2023-11-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_item_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_track_id',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
    ]
