# Generated by Django 3.2.18 on 2023-06-06 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_alter_rating_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-updated_on', '-helpful_count']},
        ),
        migrations.AddField(
            model_name='rating',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'item')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'item')},
        ),
    ]
