# Generated by Django 3.2.18 on 2023-06-06 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0021_auto_20230606_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_like',
            field=models.ManyToManyField(blank=True, editable=False, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='helpful_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
