# Generated by Django 3.2.19 on 2023-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20231127_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store_menu_name',
            field=models.CharField(blank=True, default='All', max_length=30),
        ),
    ]
