# Generated by Django 3.2.18 on 2023-06-06 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_auto_20230606_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-updated_on']},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_liked',
        ),
        migrations.AddField(
            model_name='rating',
            name='users_liked',
            field=models.ManyToManyField(blank=True, editable=False, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
