# Generated by Django 3.2.19 on 2023-11-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_item_store_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_avaliable_in',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_creator',
        ),
        migrations.AddField(
            model_name='item',
            name='product_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
    ]
