# Generated by Django 3.2.23 on 2024-01-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_order_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-updated_at', '-stars', '-id']},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
