# Generated by Django 3.2.19 on 2023-11-29 01:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_alter_store_store_menu'),
        ('product', '0025_auto_20231129_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
            preserve_default=False,
        ),
    ]
