# Generated by Django 3.2.19 on 2023-11-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_alter_store_store_menu'),
        ('product', '0028_remove_itemimage_item_image_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
        ),
    ]
