# Generated by Django 3.2.23 on 2024-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_itemimage_item_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='item_image_hash',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Item Image Hash'),
        ),
    ]
