# Generated by Django 3.2.19 on 2023-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_item_product_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=20),
        ),
    ]
