# Generated by Django 3.2.23 on 2024-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_itemimage_item_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
