# Generated by Django 3.2.23 on 2024-02-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_order_delivery_fee_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='item_image_hash',
        ),
    ]
