# Generated by Django 3.2.19 on 2023-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_item_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store_menu_name',
            field=models.CharField(blank=True, default='Others', max_length=30),
        ),
    ]
