# Generated by Django 3.2.19 on 2023-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_item_store_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_qty',
            field=models.BooleanField(default=False),
        ),
    ]
