# Generated by Django 3.2.19 on 2023-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_item_has_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='has_qty',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
