# Generated by Django 3.2.19 on 2023-12-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_item_has_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('out-for-delivery', 'out-for-delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='not-started', max_length=20),
        ),
    ]
