# Generated by Django 3.2.23 on 2024-03-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_order_vendors_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendors_seen',
            new_name='stores_seen',
        ),
    ]
