# Generated by Django 3.2.19 on 2023-12-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20231206_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
