# Generated by Django 3.2.23 on 2023-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_order_store_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('out-for-delivery', 'out-for-delivery'), ('ready-for-pickup', 'ready-for-pickup'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='not-started', max_length=20),
        ),
    ]
