# Generated by Django 3.2.23 on 2024-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_rename_stores_seen_order_profiles_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='option_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
