# Generated by Django 3.2.23 on 2023-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirm_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
