# Generated by Django 3.2.23 on 2024-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_item_option_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='option_groups',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_currency',
            field=models.CharField(default='NGN', editable=False, max_length=20),
        ),
    ]
