# Generated by Django 3.2.23 on 2023-12-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_remove_wallet_cleared_balance'),
        ('product', '0037_auto_20231218_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_person',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_people',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='linked_delivery_people',
            field=models.ManyToManyField(editable=False, related_name='linked_delivery_people', to='users.DeliveryPerson'),
        ),
    ]
