# Generated by Django 3.2.23 on 2024-03-29 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_wallet_hide_balance'),
        ('product', '0037_auto_20240330_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='store_menu_name',
            field=models.CharField(blank=True, default='OTHERS', editable=False, max_length=30),
        ),
    ]
