# Generated by Django 3.2.23 on 2024-04-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20240330_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='funds_refunded',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
