# Generated by Django 3.2.23 on 2024-04-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20240405_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_init_qty',
            field=models.PositiveBigIntegerField(default=0, help_text='Initial quantity of the product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_desc',
            field=models.CharField(blank=True, help_text='Product Description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_qty',
            field=models.PositiveBigIntegerField(default=0, help_text='Quantity of the product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='store_menu_name',
            field=models.CharField(blank=True, default='OTHERS', editable=False, help_text='Menu Name From Product Creator Store Menu', max_length=30),
        ),
    ]
