# Generated by Django 3.2.23 on 2023-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20231227_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not-started', 'not-started'), ('processing', 'processing'), ('out-for-delivery', 'out-for-delivery'), ('no-delivery-person', 'no-delivery-person'), ('ready-for-pickup', 'ready-for-pickup'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], db_index=True, default='not-started', max_length=20),
        ),
    ]
