# Generated by Django 3.2.23 on 2024-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notifications_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
