# Generated by Django 3.2.23 on 2024-04-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_order_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notifications_statuses',
        ),
    ]
