# Generated by Django 3.2.23 on 2024-04-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_remove_order_notifications_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_notified_store_of_low_stock',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
