# Generated by Django 3.2.23 on 2024-04-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_item_has_notified_store_of_low_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('suspended', 'suspended')], default='active', editable=False, max_length=20),
        ),
    ]
