# Generated by Django 3.2.23 on 2024-04-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
