# Generated by Django 3.2.23 on 2024-04-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20240429_2101'),
        ('product', '0048_delete_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store_menu_name',
        ),
        migrations.AddField(
            model_name='item',
            name='product_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.menu'),
        ),
    ]
