# Generated by Django 3.2.23 on 2024-04-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20240430_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_type',
        ),
    ]
