# Generated by Django 3.2.23 on 2024-05-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_remove_item_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('suspended', 'suspended')], default='active', max_length=20),
        ),
    ]
