# Generated by Django 3.2.23 on 2025-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_order_prev_order_track_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_slug'], name='product_ite_product_48b16b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_creator'], name='product_ite_product_2e8966_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_status'], name='product_ite_product_1a360e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_clicks'], name='product_ite_product_39efba_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_created_on'], name='product_ite_product_58ec22_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_menu'], name='product_ite_product_bedab5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_creator', 'product_status'], name='product_ite_product_458f09_idx'),
        ),
    ]
