name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch: # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use a Linux-based runner

    steps:
      - uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .  # Build context is the root of the repository
          file: Dockerfile  # Path to the Dockerfile
          push: true  # Push the built image to Docker Hub
          tags: divuzki/trayfoods-api:latest
