name: Deploy to ACR

on:
    push:
      branches:
        - master
    workflow_dispatch: # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: trayfoodsapi.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker-compose build
          docker tag trayfoodsapi.azurecr.io/trayfoods-api:latest trayfoodsapi.azurecr.io/trayfoods-api:${{ github.sha }}
          docker push trayfoodsapi.azurecr.io/trayfoods-api:${{ github.sha }}
